# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ltable.phylo <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_phylo`, LR, drop_extinct, age)
}

Ltable.prune <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_prune`, LR, age)
}

Ltable.legacy.ascending <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_legacy_ascending`, LR, age)
}

Ltable.legacy.descending <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_legacy_descending`, LR, age)
}

Ltable.cophenetic <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_cophenetic`, LR, drop_extinct, age)
}

Ltable.ed <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_ed`, LR, drop_extinct, age)
}

Ltable.nnd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_nnd`, LR, drop_extinct, age)
}

Ltable.pd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_pd`, LR, drop_extinct, age)
}

Ltable.mpd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_mpd`, LR, drop_extinct, age)
}

Ltable.tree <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_tree`, LR, drop_extinct, age)
}

Xtree <- function(Robj, drop_extinct, age = NULL) {
    .Call(`_evesim_Xtree`, Robj, drop_extinct, age)
}

Xtree.is <- function(Robj) {
    .Call(`_evesim_Xtree_is`, Robj)
}

Xtree.tips <- function(Robj) {
    .Call(`_evesim_Xtree_tips`, Robj)
}

Xtree.nnode <- function(Robj) {
    .Call(`_evesim_Xtree_nnode`, Robj)
}

Xtree.drop.extinct <- function(Robj) {
    .Call(`_evesim_Xtree_drop_extinct`, Robj)
}

Xtree.tip.label <- function(Robj) {
    .Call(`_evesim_Xtree_tip_label`, Robj)
}

Xtree.phylo <- function(Robj) {
    .Call(`_evesim_Xtree_phylo`, Robj)
}

Xtree.cophenetic <- function(Robj) {
    .Call(`_evesim_Xtree_cophenetic`, Robj)
}

Xtree.ed <- function(Robj) {
    .Call(`_evesim_Xtree_ed`, Robj)
}

Xtree.nnd <- function(Robj) {
    .Call(`_evesim_Xtree_nnd`, Robj)
}

Xtree.pd <- function(Robj) {
    .Call(`_evesim_Xtree_pd`, Robj)
}

Xtree.mpd <- function(Robj) {
    .Call(`_evesim_Xtree_mpd`, Robj)
}

SimTable <- function(Rrhs = NULL) {
    .Call(`_evesim_SimTable`, Rrhs)
}

SimTable.is <- function(Robj) {
    .Call(`_evesim_SimTable_is`, Robj)
}

SimTable.age <- function(Robj) {
    .Call(`_evesim_SimTable_age`, Robj)
}

SimTable.nspecie <- function(Robj) {
    .Call(`_evesim_SimTable_nspecie`, Robj)
}

SimTable.nclade_specie <- function(Robj) {
    .Call(`_evesim_SimTable_nclade_specie`, Robj)
}

SimTable.size <- function(Robj) {
    .Call(`_evesim_SimTable_size`, Robj)
}

#' Convert SimTable object to Legacy L-table Format
#'
#' This function extracts the simulation results from a SimTable object and converts them into
#' a legacy L-table format, represented as an R numeric matrix.
#'
#' The L-table is a common representation of evolutionary simulations, where each row corresponds to a lineage
#' with its birth, ancestor, label, and death times. This function also preserves a known flaw in the legacy L-table
#' format where the second column's first element is manually set to -1.
#'
#' @param Robj A tagged external pointer to a `sim_table_t` object, which contains the SimTable simulation results.
#'
#' @return A \code{NumericMatrix} with four columns:
#' \describe{
#'   \item{Column 1}{The birth time (t) of the lineage.}
#'   \item{Column 2}{The ancestor of the lineage.}
#'   \item{Column 3}{The label assigned to the lineage.}
#'   \item{Column 4}{The death time of the lineage, or -1 if the lineage is still extant.}
#' }
#'
#' @note For backward compatibility, the second element of the first row in the matrix (Column 2, Row 1) is set to -1 to reintroduce a known flaw in the legacy L-table format used in the DDD package.
#'
#' @examples
#' # Example usage
#' pars = c(0.5, 0.1, -0.001, -0.001, 0.0, 0.0)
#' sim_table <- evesim::edd_sim(pars = pars, age = 20, metric = "nnd", offset = "none")
#' ltable <- SimTable.ltable(sim_table$sim)
#'
#' @export
#' @useDynLib evesim
SimTable.ltable <- function(Robj) {
    .Call(`_evesim_SimTable_ltable`, Robj)
}

#' Convert SimTable object to Phylogenetic Tree
#'
#' This function extracts a phylogenetic tree from a given SimTable object and returns it in a
#' phylo-compatible format, suitable for downstream analysis in R. It can optionally remove extinct lineages
#' from the tree.
#'
#' @param Robj A tagged external pointer to a `sim_table_t` object, which contains the SimTable simulation results.
#' @param drop_extinct A logical flag indicating whether extinct lineages should be removed from the resulting phylogenetic tree.
#' \code{TRUE} will drop extinct lineages, and \code{FALSE} will return the full tree including extinct lineages.
#'
#' @return A phylo object (from the \code{ape} package) representing the phylogenetic tree extracted from the simulation table.
#'
#' @examples
#' # Example usage
#' pars = c(0.5, 0.1, -0.001, -0.001, 0.0, 0.0)
#' sim_table <- evesim::edd_sim(pars = pars, age = 20, metric = "nnd", offset = "none")
#' phylo_tree <- SimTable.phylo(sim_table$sim, drop_extinct = TRUE)
#'
#' @seealso \code{\link[ape]{phylo}} for more information about phylogenetic trees in R.
#'
#' @export
#' @useDynLib evesim
SimTable.phylo <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_phylo`, Robj, drop_extinct)
}

SimTable.tree <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_tree`, Robj, drop_extinct)
}

SimTable.speciation <- function(Robj, specie, t) {
    .Call(`_evesim_SimTable_speciation`, Robj, specie, t)
}

SimTable.extinction <- function(Robj, specie, t) {
    .Call(`_evesim_SimTable_extinction`, Robj, specie, t)
}

SimTable.tip.label <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_tip_label`, Robj, drop_extinct)
}

SimTable.cophenetic <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_cophenetic`, Robj, t)
}

SimTable.ed <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_ed`, Robj, t)
}

SimTable.nnd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_nnd`, Robj, t)
}

SimTable.pd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_pd`, Robj, t)
}

SimTable.mpd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_mpd`, Robj, t)
}

