# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

Ltable.phylo <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_phylo`, LR, drop_extinct, age)
}

Ltable.prune <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_prune`, LR, age)
}

Ltable.legacy.ascending <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_legacy_ascending`, LR, age)
}

Ltable.legacy.descending <- function(LR, age = NULL) {
    .Call(`_evesim_Ltable_legacy_descending`, LR, age)
}

Ltable.cophenetic <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_cophenetic`, LR, drop_extinct, age)
}

Ltable.ed <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_ed`, LR, drop_extinct, age)
}

Ltable.nnd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_nnd`, LR, drop_extinct, age)
}

Ltable.pd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_pd`, LR, drop_extinct, age)
}

Ltable.mpd <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_mpd`, LR, drop_extinct, age)
}

Ltable.tree <- function(LR, drop_extinct, age = NULL) {
    .Call(`_evesim_Ltable_tree`, LR, drop_extinct, age)
}

Xtree <- function(Robj, drop_extinct, age = NULL) {
    .Call(`_evesim_Xtree`, Robj, drop_extinct, age)
}

Xtree.is <- function(Robj) {
    .Call(`_evesim_Xtree_is`, Robj)
}

Xtree.tips <- function(Robj) {
    .Call(`_evesim_Xtree_tips`, Robj)
}

Xtree.nnode <- function(Robj) {
    .Call(`_evesim_Xtree_nnode`, Robj)
}

Xtree.drop.extinct <- function(Robj) {
    .Call(`_evesim_Xtree_drop_extinct`, Robj)
}

Xtree.tip.label <- function(Robj) {
    .Call(`_evesim_Xtree_tip_label`, Robj)
}

Xtree.phylo <- function(Robj) {
    .Call(`_evesim_Xtree_phylo`, Robj)
}

Xtree.cophenetic <- function(Robj) {
    .Call(`_evesim_Xtree_cophenetic`, Robj)
}

Xtree.ed <- function(Robj) {
    .Call(`_evesim_Xtree_ed`, Robj)
}

Xtree.nnd <- function(Robj) {
    .Call(`_evesim_Xtree_nnd`, Robj)
}

Xtree.pd <- function(Robj) {
    .Call(`_evesim_Xtree_pd`, Robj)
}

Xtree.mpd <- function(Robj) {
    .Call(`_evesim_Xtree_mpd`, Robj)
}

SimTable <- function(Rrhs = NULL) {
    .Call(`_evesim_SimTable`, Rrhs)
}

SimTable.is <- function(Robj) {
    .Call(`_evesim_SimTable_is`, Robj)
}

SimTable.age <- function(Robj) {
    .Call(`_evesim_SimTable_age`, Robj)
}

SimTable.nspecie <- function(Robj) {
    .Call(`_evesim_SimTable_nspecie`, Robj)
}

SimTable.nclade_specie <- function(Robj) {
    .Call(`_evesim_SimTable_nclade_specie`, Robj)
}

SimTable.size <- function(Robj) {
    .Call(`_evesim_SimTable_size`, Robj)
}

SimTable.ltable <- function(Robj) {
    .Call(`_evesim_SimTable_ltable`, Robj)
}

SimTable.phylo <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_phylo`, Robj, drop_extinct)
}

SimTable.tree <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_tree`, Robj, drop_extinct)
}

SimTable.speciation <- function(Robj, specie, t) {
    .Call(`_evesim_SimTable_speciation`, Robj, specie, t)
}

SimTable.extinction <- function(Robj, specie, t) {
    .Call(`_evesim_SimTable_extinction`, Robj, specie, t)
}

SimTable.tip.label <- function(Robj, drop_extinct) {
    .Call(`_evesim_SimTable_tip_label`, Robj, drop_extinct)
}

SimTable.cophenetic <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_cophenetic`, Robj, t)
}

SimTable.ed <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_ed`, Robj, t)
}

SimTable.nnd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_nnd`, Robj, t)
}

SimTable.pd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_pd`, Robj, t)
}

SimTable.mpd <- function(Robj, t = NULL) {
    .Call(`_evesim_SimTable_mpd`, Robj, t)
}

